In [54]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle as p

In [55]:
model=load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [56]:
with open ('label_gender.pkl','rb') as file :
    label_gender=p.load(file)

In [57]:
with open ('one_hot_geo.pkl','rb') as file :
    one_hot_geo=p.load(file)

In [58]:
with open ('Scaler.pkl','rb') as file :
    scaler=p.load(file)

In [59]:
#  Sample data 
input_data = {

'CreditScore':600,

'Geography': 'France',

'Gender': 'Male',

'Age': 40,

'Tenure': 3,

'Balance':60000,

'NumOfProducts': 2,

'HasCrCard':1,

'IsActiveMember': 1,

'EstimatedSalary': 50000

}

In [60]:
geo_encoded=one_hot_geo.transform([[input_data['Geography']]])

c:\Users\sindh\OneDrive\Apps\Desktop\DEMO\.venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [61]:
geo_encoded.toarray()

array([[1., 0., 0.]])

In [62]:
geo_encoded_df=pd.DataFrame(geo_encoded.toarray(),columns=one_hot_geo.get_feature_names_out(['Geography']))

In [63]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [64]:
input_df=pd.DataFrame([input_data])

In [65]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [66]:
input_df['Gender']=label_gender.transform(input_df['Gender'])

In [67]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [68]:
input_df.drop('Geography',axis=1,inplace=True)

In [69]:
input_df=pd.concat([input_df,geo_encoded_df],axis=1)

In [70]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [71]:
input_scaled=scaler.transform(input_df)

In [72]:
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [75]:
pred=model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

In [76]:
prediction_probability=pred[0][0]
if prediction_probability >0.5 :
    print('the customer is possibly leave')
else :
    print('customer will stay')

customer will stay